# Generated by Django 4.1 on 2023-01-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=50)),
                ('conf_passs', models.CharField(max_length=50)),
            ],
        ),
    ]
