# Generated by Django 4.1 on 2023-01-17 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('dob', models.DateField(default=datetime.datetime(2023, 1, 17, 19, 50, 6, 669537))),
                ('password', models.CharField(max_length=50)),
                ('conf_passs', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='signup',
        ),
    ]
