# Generated by Django 4.1 on 2023-01-17 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shell', '0007_alter_new_signup_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_signup',
            old_name='conf_passs',
            new_name='conf_pass',
        ),
        migrations.AlterField(
            model_name='new_signup',
            name='dob',
            field=models.DateField(default=datetime.datetime(2023, 1, 17, 20, 29, 43, 878537)),
        ),
    ]
