# Generated by Django 4.1 on 2023-01-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shell', '0008_rename_conf_passs_new_signup_conf_pass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_signup',
            name='dob',
            field=models.DateField(),
        ),
    ]
