# Generated by Django 4.1 on 2023-01-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_shell', '0009_alter_new_signup_dob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='try_new',
        ),
    ]
